#line 1 "cbu2lex.c"

#line 3 "cbu2lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[285] =
    {   0,
        0,    0,   81,   79,    1,    2,   79,   79,   79,   79,
       78,   79,   10,   77,   77,   77,   77,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,    1,
        3,   21,   73,   19,   74,   20,   22,   78,    9,   77,
        0,   77,   77,   33,   77,   77,   77,   77,   77,   71,
       12,   77,   56,   77,   77,   77,   54,   77,   77,   77,
       77,   77,   77,   66,   65,   55,   77,   77,   72,   77,
       77,   62,   67,   68,   64,   63,   77,   77,   77,   69,
       77,   77,   70,   77,   77,   35,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   34,   77,   77,   77,   76,   77,
       40,   77,   77,   77,   77,   77,   77,   57,   77,   26,
       39,   77,   38,   28,    5,   11,   77,   77,   61,   60,
       58,   77,   59,   27,   77,   77,   48,   77,   75,   77,
       46,   77,   53,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   41,   77,

       77,   49,   77,   47,   13,   77,    6,    7,   77,   50,
       77,    4,   36,   77,   77,   77,   30,   77,   17,   77,
       24,   77,   16,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   77,   77,   77,
       42,   77,   14,   31,   77,   77,   37,   77,   25,   77,
       77,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   43,   77,   77,    8,   29,   77,   77,   51,
       23,   77,   44,    0,    0,    0,    0,    0,   52,   45,
       32,   18,   15,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    1,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    9,   10,    1,
       11,    1,    1,    1,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        1,    1,    1,    1,    1,    1,   12,   12,   12,   12,

       13,   14,   12,   12,   15,   12,   12,   16,   12,   12,
       17,   12,   12,   18,   19,   12,   12,   12,   12,   12,
       12,   12,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   20,
       21,   20,   22,   20,   23,   20,   24,   25,   26,   27,
       28,   29,   20,   30,   20,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,

       33,   56,   33,   57,   58,   33,   59,   33,   60,   61,
       62,   33,   33,   63,   33,   64,   65,   33,   66,   33,
       67,   33,   33,   68,   33,   69,   33,   70,   33,   33,
       71,   33,   72,   73,   33,   33,   33,   33,   74,   33,
       33,   33,   75,   33,   76,   77,   33,   33,   33,   33,
       33,   78,   33,   33,    1
    } ;

static const YY_CHAR yy_meta[79] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[288] =
    {   0,
        0,    0,  776,  810,   77,   79,  763,   78,   79,  761,
      756,  743,  810,   79,   91,  103,  115,  114,  707,    0,
      115,   37,  682,  666,  661,  690,  657,  683,   75,  668,
       87,  658,  112,   94,   87,  687,   86,  651,  641,  152,
      154,  810,  810,  810,  810,  810,  810,  684,  810,  153,
        0,  171,  184,  196,  208,  220,  198,  209,  200,  211,
      217,  231,  224,  228,  234,  237,  243,  254,  251,  257,
      266,  265,  279,  268,  277,  283,  285,  291,  292,  305,
      311,  303,  317,  318,  320,  331,  340,  330,  342,  348,
      349,  350,  357,  359,  372,  360,  654,  617,  653,  598,

      628,  575,  536,  552,  578,  523,  507,  546,  528,  502,
      487,  508,  482,  509,  472,  462,  453,  439,  445,  468,
      409,  441,  419,  390,  436,  406,  430,  385,  382,  414,
      380,  363,  397,  389,  368,  379,  382,  390,  391,  399,
      392,  402,  409,  421,  417,  424,  432,  431,  443,  439,
      441,  450,  451,  454,  458,  461,  469,  480,  468,  481,
      483,  487,  491,  493,  495,  505,  494,  513,  517,  524,
      523,  531,  532,  343,  328,  346,  321,  324,  301,  289,
      300,  284,  278,  264,  268,  301,  258,  304,  291,  255,
      219,  250,  260,  209,  230,  196,  222,  176,  535,  541,

      558,  543,  560,  549,  550,  568,  567,  569,  577,  575,
      586,  578,  587,  597,  595,  606,  604,  605,  615,  629,
      617,  619,  623,  174,  192,  191,  152,  178,  136,  184,
      145,  131,  121,  150,  159,  128,  146,  630,  637,  641,
      643,  649,  647,  655,  656,  666,  667,  681,  673,  674,
      696,  111,  144,  143,  100,   98,  119,  131,   87,   84,
      120,   79,  692,  703,  705,  704,  706,  714,  716,  718,
      728,  736,  738,   75,   61,   30,   18,   14,  740,  742,
      746,  748,  750,  810,  801,  803,  805
    } ;

static const flex_int16_t yy_def[288] =
    {   0,
      284,    1,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  285,  285,  285,  285,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  285,
      287,  285,  285,  285,  285,  285,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,   56,   56,

       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  287,  287,  287,  287,  287,   56,   56,
       56,   56,   56,    0,  284,  284,  284
    } ;

static const flex_int16_t yy_nxt[889] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
        4,   14,   15,   16,   17,   14,   14,   14,   14,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   20,   20,
       36,   37,   38,   39,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   40,   41,
       41,   41,   43,  283,   45,   64,   50,  282,   44,   46,
       50,   50,   50,   50,   50,   50,   50,   50,   50,  281,

       73,   65,   50,   50,   50,   50,   52,   50,   50,   50,
       50,   91,   66,   92,   50,   50,   50,   50,   50,   53,
       50,   50,   50,   88,   84,  280,   50,   50,   54,   50,
       50,   50,   50,   50,   56,   61,   77,   81,   57,  279,
       78,   62,   79,  273,   58,   74,  272,   82,   75,  271,
       85,  270,   86,   40,   41,   41,   41,  269,   83,   87,
       50,  268,   89,  267,   50,   50,   50,   50,   50,   50,
       50,   50,  266,  265,  264,  263,  251,  250,   50,  249,
      248,   63,   50,   50,   50,   50,   50,   50,   50,   95,
       59,   50,  247,  246,  245,   50,   50,   50,   50,   50,

       50,   96,   50,   50,  244,  243,  242,   50,   50,   50,
       50,   50,   50,   50,   50,   50,  241,  240,  239,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   51,  238,
       51,   50,   50,   50,   50,   50,   50,   50,   50,   51,
      100,   51,  101,  102,   51,  223,   51,   51,  222,   51,
       97,   51,  221,  104,   51,   51,  103,   51,   51,  220,
       51,   51,   51,   51,   51,  105,   98,   51,   51,  106,
       51,   99,  108,   51,  107,   51,  109,   51,  219,   51,
       51,   51,   51,   51,   51,   51,  218,   51,   51,   51,
      110,  217,  111,  216,   51,   51,   51,   51,   51,  115,

       51,  113,   51,   51,  112,   51,  114,   51,   51,   51,
      116,   51,   51,   51,   51,   51,   51,   51,  215,   51,
      214,   51,   51,   51,  213,   51,  212,  211,   51,   51,
       51,  117,  210,   51,   51,   51,   51,   51,   51,  119,
      209,   51,   51,   51,  118,  121,  208,   51,   51,   51,
      123,   51,  207,  122,   51,  206,   51,   51,  205,  120,
      129,  124,   51,   51,   51,  204,   51,  125,   51,   51,
      126,   51,  130,  127,  128,  203,   51,   51,   51,  131,
      133,   51,   51,  132,  135,  202,   51,   51,   51,   51,
       51,   51,  134,   51,   51,   51,   51,  201,   51,   51,

       51,   51,   51,   51,  200,   51,   51,  199,   51,   51,
       51,   51,  176,  174,   51,  173,  177,  172,   51,   51,
      178,   51,   51,   51,  179,   51,  175,  171,   51,   51,
       51,  170,   51,   51,  169,  168,   51,   51,   51,   51,
      182,   51,   51,   51,  180,   51,  181,   51,   51,  167,
       51,   51,  183,   51,   51,   51,  166,  165,  185,  164,
       51,   51,   51,   51,  184,  186,  163,   51,   51,   51,
       51,   51,   51,   51,  187,   51,  162,   51,   51,  161,
       51,   51,   51,   51,   51,   51,  160,   51,   51,   51,
       51,   51,   51,  159,   51,  188,   51,   51,   51,   51,

       51,   51,   51,  158,   51,   51,  157,   51,  189,   51,
       51,   51,   51,   51,   51,   51,  191,   51,  156,   51,
       51,   51,  190,   51,   51,   51,   51,   51,  193,   51,
      155,   51,   51,  192,   51,   51,  154,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,  153,  152,
      194,   51,  195,   51,   51,  151,   51,  197,  150,  196,
      149,   51,   51,   51,   51,   51,  148,  147,   51,   51,
       51,   51,  146,   51,   51,   51,  198,   51,   51,   51,
       51,   51,   51,   51,  145,  224,   51,   51,   51,   51,
       51,  225,   51,  226,   51,   51,   51,   51,   51,   51,

       51,   51,  227,  144,   51,   51,   51,   51,   51,   51,
      143,   51,  142,   51,   51,   51,   51,   51,   51,   51,
       51,   51,  228,   51,   51,   51,   51,   51,   51,   51,
      230,  229,   51,   51,   51,  234,   51,   51,   51,  141,
      231,   51,  232,   51,  233,   51,   51,   51,   51,  237,
       51,   51,   51,   51,  140,   51,   51,   51,  139,   51,
       51,   51,  235,   51,  252,   51,   51,  253,   51,   51,
       51,  254,  236,   51,   51,   51,   51,   51,  138,   51,
       51,   51,  137,   51,  136,   51,   51,   51,   51,   51,
      255,   48,   51,   51,   51,   51,   51,   51,   51,   94,

       51,   51,  256,   51,   51,   93,   51,   51,  257,   90,
       80,   51,   51,   51,  258,  259,   76,   51,   51,   51,
      260,   72,   51,   71,   51,   51,   51,   51,   70,  261,
      262,   69,   51,   51,   51,   51,   51,  274,   51,  275,
       68,   67,   51,   51,   51,   60,   51,   51,   51,   51,
       51,   51,   51,   49,   51,   51,   51,   51,   51,  276,
       51,  277,   51,   48,   51,   51,   51,   51,   51,   51,
       51,   47,   51,   42,   51,  284,   51,  284,   51,   51,
       51,  278,   51,  284,   51,  284,   51,   51,   51,   51,
      284,   51,   51,   51,   51,  284,   51,   51,  284,   51,

      284,   51,   51,  284,   51,   55,   55,   50,   50,    3,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284
    } ;

static const flex_int16_t yy_chk[889] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        6,    6,    8,  278,    9,   22,   14,  277,    8,    9,
       14,   14,   14,   14,   14,   14,   14,   14,   15,  276,

       29,   22,   15,   15,   15,   15,   15,   15,   15,   15,
       16,   37,   22,   37,   16,   16,   16,   16,   16,   16,
       16,   16,   17,   35,   34,  275,   17,   17,   17,   17,
       17,   17,   17,   17,   18,   21,   31,   33,   18,  274,
       31,   21,   31,  262,   18,   29,  261,   33,   29,  260,
       34,  259,   34,   40,   40,   41,   41,  258,   33,   34,
       50,  257,   35,  256,   50,   50,   50,   50,   50,   50,
       50,   50,  255,  254,  253,  252,  237,  236,   52,  235,
      234,   21,   52,   52,   52,   52,   52,   52,   52,   52,
       18,   53,  233,  232,  231,   53,   53,   53,   53,   53,

       53,   53,   53,   54,  230,  229,  228,   54,   54,   54,
       54,   54,   54,   54,   54,   55,  227,  226,  225,   55,
       55,   55,   55,   55,   55,   55,   55,   56,   57,  224,
       59,   56,   56,   56,   56,   56,   56,   56,   56,   58,
       57,   60,   58,   58,   57,  198,   59,   61,  197,   57,
       56,   59,  196,   59,   63,   58,   58,   60,   64,  195,
       58,   62,   60,   61,   65,   62,   56,   66,   61,   62,
       63,   56,   65,   67,   64,   63,   65,   62,  194,   64,
       65,   69,   62,   66,   68,   65,  193,   70,   66,   67,
       66,  192,   68,  191,   67,   72,   71,   69,   74,   72,

       68,   70,   69,   70,   69,   68,   71,   75,   70,   73,
       73,   72,   71,   76,   74,   77,   72,   71,  190,   74,
      189,   78,   79,   75,  188,   73,  187,  186,   75,   76,
       73,   77,  185,   82,   76,   80,   77,   78,   79,   80,
      184,   81,   78,   79,   78,   81,  183,   83,   84,   82,
       85,   80,  182,   81,   82,  181,   80,   81,  180,   80,
       88,   86,   81,   83,   84,  179,   85,   86,   83,   84,
       87,   85,   89,   87,   87,  178,   88,   86,   90,   91,
       92,   88,   86,   91,   95,  177,   87,   93,   89,   94,
       96,   87,   94,   89,   90,   91,   92,  176,  135,   90,

       91,   92,   95,   93,  175,   94,   96,  174,   93,  136,
       94,   96,  137,  136,  135,  134,  137,  133,   95,  135,
      138,  139,  141,   95,  138,  136,  136,  132,  137,  140,
      136,  131,  142,  137,  130,  129,  138,  139,  141,  143,
      143,  138,  139,  141,  140,  140,  142,  145,  142,  128,
      140,  144,  144,  142,  146,  143,  127,  126,  146,  125,
      143,  148,  147,  145,  145,  147,  124,  144,  145,  150,
      146,  151,  144,  149,  149,  146,  123,  148,  147,  122,
      152,  153,  148,  147,  154,  150,  121,  151,  155,  149,
      150,  156,  151,  120,  149,  152,  152,  153,  159,  157,

      154,  152,  153,  119,  155,  154,  118,  156,  157,  155,
      158,  160,  156,  161,  159,  157,  158,  162,  117,  159,
      157,  163,  157,  164,  167,  165,  158,  160,  165,  161,
      116,  158,  160,  162,  161,  166,  115,  163,  162,  164,
      167,  165,  163,  168,  164,  167,  165,  169,  114,  113,
      166,  166,  168,  171,  170,  112,  166,  170,  111,  168,
      110,  172,  173,  169,  168,  199,  109,  108,  169,  171,
      170,  200,  107,  202,  171,  170,  172,  172,  173,  204,
      205,  199,  172,  173,  106,  200,  199,  200,  201,  202,
      203,  201,  200,  203,  202,  204,  205,  207,  206,  208,

      204,  205,  206,  105,  201,  210,  203,  209,  212,  201,
      104,  203,  103,  207,  206,  208,  211,  213,  207,  206,
      208,  210,  209,  209,  212,  215,  210,  214,  209,  212,
      214,  211,  211,  213,  217,  218,  216,  211,  213,  102,
      214,  215,  215,  214,  216,  219,  215,  221,  214,  222,
      217,  218,  216,  223,  101,  217,  218,  216,  100,  220,
      238,  219,  220,  221,  238,  222,  219,  239,  221,  223,
      222,  240,  220,  241,  223,  220,  238,  243,   99,  242,
      220,  238,   98,  239,   97,  244,  245,  240,  239,  241,
      242,   48,  240,  243,  241,  242,  246,  247,  243,   39,

      242,  244,  245,  249,  250,   38,  244,  245,  246,   36,
       32,  248,  246,  247,  248,  248,   30,  246,  247,  249,
      250,   28,  263,   27,  249,  250,  251,  248,   26,  251,
      251,   25,  248,  264,  266,  265,  267,  264,  263,  265,
       24,   23,  251,  263,  268,   19,  269,  251,  270,  264,
      266,  265,  267,   12,  264,  266,  265,  267,  271,  268,
      268,  269,  269,   11,  270,  268,  272,  269,  273,  270,
      279,   10,  280,    7,  271,    3,  281,    0,  282,  271,
      283,  272,  272,    0,  273,    0,  279,  272,  280,  273,
        0,  279,  281,  280,  282,    0,  283,  281,    0,  282,

        0,  283,  285,    0,  285,  286,  286,  287,  287,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cbu2.l"
#line 2 "cbu2.l"
#include <string.h>
#include "cbu2.h"
#define MAXSYM	100
#define	MAXSYMLEN	20
char symtbl[MAXSYM][MAXSYMLEN];
int lineno=1;
int insertsym();
int maxsym=0;
char s[MAXSYMLEN];
int temp;

#pragma warning(disable : 4996)


#line 745 "cbu2lex.c"
#line 746 "cbu2lex.c"

#define INITIAL 0

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 25 "cbu2.l"

#line 962 "cbu2lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 810 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "cbu2.l"
{/* do nothing */}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 27 "cbu2.l"
{lineno++; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 28 "cbu2.l"
; // Ignore whitespace
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "cbu2.l"
{return(ADD); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "cbu2.l"
{return(SUB); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "cbu2.l"
{return(MUL); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "cbu2.l"
{return(DIV); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "cbu2.l"
{ return(MOD); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "cbu2.l"
{return(ASSGN); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "cbu2.l"
{return(STMTEND); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 40 "cbu2.l"
{return(START); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 41 "cbu2.l"
{return(END); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 43 "cbu2.l"
{ return(EQUAL); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 44 "cbu2.l"
{ return(NOTEQUAL); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "cbu2.l"
{ return(GREATEREQUAL); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 46 "cbu2.l"
{ return(GREATER); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 47 "cbu2.l"
{ return(LESS); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 48 "cbu2.l"
{ return(LESSEQUAL); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "cbu2.l"
{ return(ASSGNADD); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "cbu2.l"
{ return(ASSGNSUB); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "cbu2.l"
{ return(ASSGNMUL); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "cbu2.l"
{ return(ASSGNDIV); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 55 "cbu2.l"
{ return(LEFTPAR); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 56 "cbu2.l"
{ return(LEFTPAR); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 57 "cbu2.l"
{ return(RIGHTPAR); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 58 "cbu2.l"
{ return(RIGHTPAR); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 59 "cbu2.l"
{ return(RIGHTPAR); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 60 "cbu2.l"
{ return(RIGHTPAR); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 61 "cbu2.l"
{ return(LEFTBLOCK); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 62 "cbu2.l"
{ return(LEFTBLOCK); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 63 "cbu2.l"
{ return(RIGHTBLOCK); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 64 "cbu2.l"
{ return(RIGHTBLOCK); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "cbu2.l"
{ return(IF); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "cbu2.l"
{ return(ELSE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "cbu2.l"
{ return(FOR); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "cbu2.l"
{ return(IF); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "cbu2.l"
{ return(ELSE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "cbu2.l"
{ return(FOR); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "cbu2.l"
{ return(WHILE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "cbu2.l"
{ return(CONDEQUAL); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "cbu2.l"
{ return(CONDEQUAL); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 79 "cbu2.l"
{ return(CONDNOTEQUAL); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 80 "cbu2.l"
{ return(CONDNOTEQUAL); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 82 "cbu2.l"
{ return(CONDGREATEREQUAL); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 83 "cbu2.l"
{ return(CONDGREATEREQUAL); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "cbu2.l"
{ return(CONDGREATER); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "cbu2.l"
{ return(CONDGREATER); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "cbu2.l"
{ return(CONDELESS); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "cbu2.l"
{ return(CONDELESS); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "cbu2.l"
{ return(CONDELESS); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "cbu2.l"
{ return(CONDLESSEQUAL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "cbu2.l"
{ return(CONDLESSEQUAL); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "cbu2.l"
{ return(ONE); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "cbu2.l"
{ return(TWO); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "cbu2.l"
{ return(THREE); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "cbu2.l"
{ return(FOUR); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "cbu2.l"
{ return(FIVE); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "cbu2.l"
{ return(SIX); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "cbu2.l"
{ return(SEVEN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "cbu2.l"
{ return(EIGHT); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 "cbu2.l"
{ return(NINE); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 "cbu2.l"
{ return(ZERO); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "cbu2.l"
{ return(ONE); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "cbu2.l"
{ return(TWO); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "cbu2.l"
{ return(THREE); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "cbu2.l"
{ return(FOUR); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "cbu2.l"
{ return(FIVE); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "cbu2.l"
{ return(SIX); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "cbu2.l"
{ return(SEVEN); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "cbu2.l"
{ return(EIGHT); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 114 "cbu2.l"
{ return(NINE); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 115 "cbu2.l"
{ return(TEN); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 117 "cbu2.l"
{ return(INCREASE); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 118 "cbu2.l"
{ return(DECREASE); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 119 "cbu2.l"
{ return(INCREASE); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 120 "cbu2.l"
{ return(DECREASE); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 122 "cbu2.l"
{temp=insertsym(yytext); yylval=MakeNode(ID, temp); return(ID);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 123 "cbu2.l"
{sscanf(yytext, "%d", &temp); yylval=MakeNode(NUM, temp); return(NUM);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 124 "cbu2.l"
{printf("invalid token %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 125 "cbu2.l"
ECHO;
	YY_BREAK
#line 1421 "cbu2lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 284);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 125 "cbu2.l"


int insertsym(s)
char *s;
{
int i;

	for(i=0;i<maxsym; i++) {
		if(strcmp(s, symtbl[i])==0) return(i);
		}
	if (i<MAXSYM-1) {
		strcpy(symtbl[maxsym],s);
		maxsym++;
		return(maxsym-1);
		}
	else
		{printf("symbol table overflow\n");}
	return(0);
}

yywrap() {}
